# PART I

# 1. Importing Pandas and Loading Data

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Load CSV file into a DataFrame

df=pd.read_csv('https://raw.githubusercontent.com/renatomaaliw3/public_files/refs/heads/master/Data%20Sets/healthcare_dataset.csv')
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,31 01 2024,Matthew Smith,Sons and Miller,Blue Cross,18856.281310,328,Urgent,2 02 2024,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,20 08 2019,Samantha Davies,Kim Inc,Medicare,33643.327290,265,Emergency,26 08 2019,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,22 09 2022,Tiffany Mitchell,Cook PLC,Aetna,27955.096080,205,Emergency,7 10 2022,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,18 11 2020,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,18 12 2020,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,19 09 2022,Kathleen Hanna,White-White,Aetna,14238.317810,458,Urgent,9 10 2022,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,16 08 2020,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,15 09 2020,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,23 01 2020,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797310,316,Elective,1 02 2020,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,13 07 2020,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764720,347,Urgent,10 08 2020,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,25 05 2019,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092360,321,Elective,31 05 2019,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2 04 2024,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,29 04 2024,Ibuprofen,Abnormal

# 2. Cleaning and Exploring The Dataset

In [ ]:
# Display first five rows of the DataFrame

print("First five rows:\n", df.head())

First five rows:
             Name  Age  Gender Blood Type Medical Condition Date of Admission  \
0  Bobby JacksOn   30    Male         B-            Cancer        31 01 2024
1   LesLie TErRy   62    Male         A+           Obesity        20 08 2019
2    DaNnY sMitH   76  Female         A-           Obesity        22 09 2022
3   andrEw waTtS   28  Female         O+          Diabetes        18 11 2020
4  adrIENNE bEll   43  Female        AB+            Cancer        19 09 2022

             Doctor                    Hospital Insurance Provider  \
0     Matthew Smith             Sons and Miller         Blue Cross
1   Samantha Davies                     Kim Inc           Medicare
2  Tiffany Mitchell                    Cook PLC              Aetna
3       Kevin Wells  Hernandez Rogers and Vang,           Medicare
4    Kathleen Hanna                 White-White              Aetna

   Billing Amount  Room Number Admission Type Discharge Date   Medication  \
0     18856.28131          328         Urgent      2 02 2024  Paracetamol
1     33643.32729          265      Emergency     26 08 2019    Ibuprofen
2     27955.09608          205      Emergency      7 10 2022      Aspirin
3     37909.78241          450       Elective     18 12 2020    Ibuprofen
4     14238.31781          458         Urgent      9 10 2022   Penicillin

   Test Results
0        Normal
1  Inconclusive
2        Normal
3      Abnormal
4      Abnormal

In [ ]:
# Check for missing values

print("Missing values:\n", df.isnull().sum())

Missing values:
 Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [ ]:
# Filter rows where 'age' column is greater than 40.

filtered_df=df[df['Age']>40]
print("Rows where age is greater than 30:\n", filtered_df)

Rows where age is greater than 30:
                     Name  Age  Gender Blood Type Medical Condition  \
1           LesLie TErRy   62    Male         A+           Obesity
2            DaNnY sMitH   76  Female         A-           Obesity
4          adrIENNE bEll   43  Female        AB+            Cancer
8        JASmINe aGuIlaR   82    Male        AB+            Asthma
9       ChRISTopher BerG   58  Female        AB-            Cancer
...                  ...  ...     ...        ...               ...
55494      JEssIcA WHiTe   67    Male         O+         Arthritis
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma
55496         KYle pEREz   61  Female        AB-           Obesity
55498     JENniFER JOneS   43    Male         O-         Arthritis
55499       jAMES GARCiA   53  Female         O+         Arthritis

      Date of Admission            Doctor                  Hospital  \
1            20 08 2019   Samantha Davies                   Kim Inc
2            22 09 2022  Tiffany Mitchell                  Cook PLC
4            19 09 2022    Kathleen Hanna               White-White
8             1 07 2020   Daniel Ferguson             Sons Rich and
9            23 04 2021       Heather Day            Padilla-Walker
...                 ...               ...                       ...
55494        11 12 2023      Jesus Jordan             Miller-Harris
55495        16 08 2020     Joshua Jarvis            Jones-Thompson
55496        23 01 2020   Taylor Sullivan              Tucker-Moyer
55498        25 05 2019    Kimberly Curry  Jackson Todd and Castro,
55499         2 04 2024     Dennis Warren            Henry Sons and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
1               Medicare    33643.327290          265      Emergency
2                  Aetna    27955.096080          205      Emergency
4                  Aetna    14238.317810          458         Urgent
8                  Cigna    50119.222790          316       Elective
9       UnitedHealthcare    19784.631060          249       Elective
...                  ...             ...          ...            ...
55494           Medicare    42535.301230          378      Emergency
55495         Blue Cross     2650.714952          417       Elective
55496              Cigna    31457.797310          316       Elective
55498           Medicare    32451.092360          321       Elective
55499              Aetna     4010.134172          448         Urgent

      Discharge Date   Medication  Test Results
1         26 08 2019    Ibuprofen  Inconclusive
2          7 10 2022      Aspirin        Normal
4          9 10 2022   Penicillin      Abnormal
8         14 07 2020      Aspirin      Abnormal
9         22 06 2021  Paracetamol  Inconclusive
...              ...          ...           ...
55494      4 01 2024    Ibuprofen        Normal
55495     15 09 2020   Penicillin      Abnormal
55496      1 02 2020      Aspirin        Normal
55498     31 05 2019    Ibuprofen      Abnormal
55499     29 04 2024    Ibuprofen      Abnormal

[36876 rows x 15 columns]

In [ ]:
# Sort DataFrame by 'age' in descending order.

sorted_df=df.sort_values(by='Age',ascending=True)
print("DataFrame sorted by age:\n", sorted_df)

DataFrame sorted by age:
                     Name  Age  Gender Blood Type Medical Condition  \
50908       rOnalD daVis   13    Male         A+           Obesity
51900     jAcob wILLiAMs   13  Female         A+           Obesity
51873    doRothY hoffMAn   13  Female         O-            Cancer
50823      DEaNnA pALMeR   13    Male        AB-           Obesity
51833   JoNaTHAn JacksoN   13  Female         B-           Obesity
...                  ...  ...     ...        ...               ...
52828       doNALD aViLA   89  Female        AB-            Asthma
54813  JerEmY hArdIN JR.   89    Male         A+          Diabetes
55385     hEAthEr dawsOn   89    Male         O-         Arthritis
52857    THomAs PHIllIpS   89  Female         A+      Hypertension
52043       DAVId NeWTOn   89  Female         O+         Arthritis

      Date of Admission             Doctor                     Hospital  \
50908         6 12 2023     Shannon Butler    Kelly, and Gomez Williams
51900         3 03 2020     Samantha Scott        and Huerta, Cox Price
51873        18 07 2020      Suzanne Jones       Davis Davis, and Davis
50823        20 09 2020     Barbara Butler  and Sanchez Phillips, Brown
51833         7 02 2020     Kevin Friedman              Spencer-Shields
...                 ...                ...                          ...
52828        17 09 2022  Christopher Allen    Holmes and Howard Castro,
54813         5 11 2019     Willie Stevens                 Gray-Solomon
55385        18 07 2022           Ann Hall                   Moore-Gray
52857        22 05 2022         Mark White     and Martin, Davidson Cox
52043         8 02 2021      Jerry Hopkins      Cooper Brown Parks, and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
50908              Cigna     3014.565852          241      Emergency
51900           Medicare    42349.109220          373         Urgent
51873              Cigna    22316.169320          379       Elective
50823           Medicare    23941.759490          163      Emergency
51833           Medicare    30075.230980          472         Urgent
...                  ...             ...          ...            ...
52828              Aetna    14042.748910          199      Emergency
54813              Cigna     7242.641277          113       Elective
55385              Aetna    17172.115990          455       Elective
52857              Cigna    48274.348630          332         Urgent
52043              Aetna    34500.016820          242       Elective

      Discharge Date   Medication  Test Results
50908      4 01 2024  Paracetamol        Normal
51900     20 03 2020    Ibuprofen        Normal
51873     10 08 2020    Ibuprofen      Abnormal
50823     23 09 2020   Penicillin  Inconclusive
51833     24 02 2020      Aspirin  Inconclusive
...              ...          ...           ...
52828     27 09 2022      Aspirin      Abnormal
54813     28 11 2019   Penicillin        Normal
55385     13 08 2022    Ibuprofen        Normal
52857     26 05 2022   Penicillin  Inconclusive
52043     20 02 2021   Penicillin  Inconclusive

[55500 rows x 15 columns]

# 3. GroupBy

In [ ]:
# Group by 'Hospital' and computing the average age per hospitals

df.groupby('Hospital')['Age'].mean()

Hospital
Abbott Inc                       59.0
Abbott Ltd                       59.0
Abbott Moore and Williams,       39.0
Abbott and Thompson, Sullivan    84.0
Abbott, Peters and Hoffman       62.5
                                 ...
and Zimmerman Sons               72.0
and Zuniga Davis Carlson,        23.0
and Zuniga Francis Peterson,     57.0
and Zuniga Sons                  71.0
and Zuniga Thompson, Blake       19.0
Name: Age, Length: 39876, dtype: float64

# 4. Visualizations

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [ ]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224655    202.000000
50%       52.000000    25538.069380    302.000000
75%       68.000000    37820.508432    401.000000
max       89.000000    52764.276740    500.000000

My analysis from this dataset is/are the following:
1. When the data is cleaned, there's no missing values on the data
2. Pandas is very helpful in Data Manipulation, Filtering, and Analyzing the dataset you used. It helps us to understand info based on what you want to know (mean, sum, and many more)
3. The dataset was cleaned and we use Python code/s to show the information of the given/used dataset for finding the missing values, data types, and, other information by using df.info()
4. We also used df.describe() to show the count, mean, std, min, 25%, 50%, 75%, and the max of the used dataset.

- In conclusion, the Pandas (Python library) helps us to manipulate data and create analysis, proving data structures like DataFrame and Series.

# PART II

## 1. Importing Pandas and Loading Data

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Load CSV file into a DataFrame

df=pd.read_csv('https://raw.githubusercontent.com/renatomaaliw3/public_files/refs/heads/master/Data%20Sets/healthcare_dataset.csv')
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,31 01 2024,Matthew Smith,Sons and Miller,Blue Cross,18856.281310,328,Urgent,2 02 2024,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,20 08 2019,Samantha Davies,Kim Inc,Medicare,33643.327290,265,Emergency,26 08 2019,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,22 09 2022,Tiffany Mitchell,Cook PLC,Aetna,27955.096080,205,Emergency,7 10 2022,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,18 11 2020,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,18 12 2020,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,19 09 2022,Kathleen Hanna,White-White,Aetna,14238.317810,458,Urgent,9 10 2022,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,16 08 2020,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,15 09 2020,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,23 01 2020,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797310,316,Elective,1 02 2020,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,13 07 2020,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764720,347,Urgent,10 08 2020,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,25 05 2019,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092360,321,Elective,31 05 2019,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2 04 2024,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,29 04 2024,Ibuprofen,Abnormal

In [ ]:
print("DataFrame Head:\n", df.head())

DataFrame Head:
             Name  Age  Gender Blood Type Medical Condition Date of Admission  \
0  Bobby JacksOn   30    Male         B-            Cancer        31 01 2024
1   LesLie TErRy   62    Male         A+           Obesity        20 08 2019
2    DaNnY sMitH   76  Female         A-           Obesity        22 09 2022
3   andrEw waTtS   28  Female         O+          Diabetes        18 11 2020
4  adrIENNE bEll   43  Female        AB+            Cancer        19 09 2022

             Doctor                    Hospital Insurance Provider  \
0     Matthew Smith             Sons and Miller         Blue Cross
1   Samantha Davies                     Kim Inc           Medicare
2  Tiffany Mitchell                    Cook PLC              Aetna
3       Kevin Wells  Hernandez Rogers and Vang,           Medicare
4    Kathleen Hanna                 White-White              Aetna

   Billing Amount  Room Number Admission Type Discharge Date   Medication  \
0     18856.28131          328         Urgent      2 02 2024  Paracetamol
1     33643.32729          265      Emergency     26 08 2019    Ibuprofen
2     27955.09608          205      Emergency      7 10 2022      Aspirin
3     37909.78241          450       Elective     18 12 2020    Ibuprofen
4     14238.31781          458         Urgent      9 10 2022   Penicillin

   Test Results
0        Normal
1  Inconclusive
2        Normal
3      Abnormal
4      Abnormal

# 2. Exploring The DataFrame

In [ ]:
# Display first five rows of the DataFrame

print("First five rows:\n", df.head())

First five rows:
             Name  Age  Gender Blood Type Medical Condition Date of Admission  \
0  Bobby JacksOn   30    Male         B-            Cancer        31 01 2024
1   LesLie TErRy   62    Male         A+           Obesity        20 08 2019
2    DaNnY sMitH   76  Female         A-           Obesity        22 09 2022
3   andrEw waTtS   28  Female         O+          Diabetes        18 11 2020
4  adrIENNE bEll   43  Female        AB+            Cancer        19 09 2022

             Doctor                    Hospital Insurance Provider  \
0     Matthew Smith             Sons and Miller         Blue Cross
1   Samantha Davies                     Kim Inc           Medicare
2  Tiffany Mitchell                    Cook PLC              Aetna
3       Kevin Wells  Hernandez Rogers and Vang,           Medicare
4    Kathleen Hanna                 White-White              Aetna

   Billing Amount  Room Number Admission Type Discharge Date   Medication  \
0     18856.28131          328         Urgent      2 02 2024  Paracetamol
1     33643.32729          265      Emergency     26 08 2019    Ibuprofen
2     27955.09608          205      Emergency      7 10 2022      Aspirin
3     37909.78241          450       Elective     18 12 2020    Ibuprofen
4     14238.31781          458         Urgent      9 10 2022   Penicillin

   Test Results
0        Normal
1  Inconclusive
2        Normal
3      Abnormal
4      Abnormal

In [ ]:
# Check for missing values

print("Missing values:\n", df.isnull().sum())

Missing values:
 Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [ ]:
# Get summary statistics

print("Summary statistics:\n", df.describe())

Summary statistics:
                 Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224655    202.000000
50%       52.000000    25538.069380    302.000000
75%       68.000000    37820.508432    401.000000
max       89.000000    52764.276740    500.000000

# 3. Filtering and Sorting Data

In [ ]:
# Filter rows where 'age' column is greater than 30

filtered_df=df[df['Age']>30]
print("Rows where age is greater than 30:\n", filtered_df)

Rows where age is greater than 30:
                     Name  Age  Gender Blood Type Medical Condition  \
1           LesLie TErRy   62    Male         A+           Obesity
2            DaNnY sMitH   76  Female         A-           Obesity
4          adrIENNE bEll   43  Female        AB+            Cancer
5          EMILY JOHNSOn   36    Male         A+            Asthma
8        JASmINe aGuIlaR   82    Male        AB+            Asthma
...                  ...  ...     ...        ...               ...
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma
55496         KYle pEREz   61  Female        AB-           Obesity
55497       HEATher WaNG   38  Female         B+      Hypertension
55498     JENniFER JOneS   43    Male         O-         Arthritis
55499       jAMES GARCiA   53  Female         O+         Arthritis

      Date of Admission            Doctor                      Hospital  \
1            20 08 2019   Samantha Davies                       Kim Inc
2            22 09 2022  Tiffany Mitchell                      Cook PLC
4            19 09 2022    Kathleen Hanna                   White-White
5            20 12 2023     Taylor Newton                Nunez-Humphrey
8             1 07 2020   Daniel Ferguson                 Sons Rich and
...                 ...               ...                           ...
55495        16 08 2020     Joshua Jarvis                Jones-Thompson
55496        23 01 2020   Taylor Sullivan                  Tucker-Moyer
55497        13 07 2020    Joe Jacobs DVM  and Mahoney Johnson Vasquez,
55498        25 05 2019    Kimberly Curry      Jackson Todd and Castro,
55499         2 04 2024     Dennis Warren                Henry Sons and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
1               Medicare    33643.327290          265      Emergency
2                  Aetna    27955.096080          205      Emergency
4                  Aetna    14238.317810          458         Urgent
5       UnitedHealthcare    48145.110950          389         Urgent
8                  Cigna    50119.222790          316       Elective
...                  ...             ...          ...            ...
55495         Blue Cross     2650.714952          417       Elective
55496              Cigna    31457.797310          316       Elective
55497   UnitedHealthcare    27620.764720          347         Urgent
55498           Medicare    32451.092360          321       Elective
55499              Aetna     4010.134172          448         Urgent

      Discharge Date  Medication  Test Results
1         26 08 2019   Ibuprofen  Inconclusive
2          7 10 2022     Aspirin        Normal
4          9 10 2022  Penicillin      Abnormal
5         24 12 2023   Ibuprofen        Normal
8         14 07 2020     Aspirin      Abnormal
...              ...         ...           ...
55495     15 09 2020  Penicillin      Abnormal
55496      1 02 2020     Aspirin        Normal
55497     10 08 2020   Ibuprofen      Abnormal
55498     31 05 2019   Ibuprofen      Abnormal
55499     29 04 2024   Ibuprofen      Abnormal

[45001 rows x 15 columns]

In [ ]:
# Sort DataFrame by 'age' in descending order

sorted_df=df.sort_values(by='Age',ascending=False)
print("DataFrame sorted by age:\n", sorted_df.head())

DataFrame sorted by age:
                     Name  Age  Gender Blood Type Medical Condition  \
53825      mIchaeL POtTs   89    Male         A+      Hypertension
52857    THomAs PHIllIpS   89  Female         A+      Hypertension
52372    DeBORah McBrIdE   89  Female         O+           Obesity
54044  MiChAEL DOmINGuEz   89    Male         O+            Cancer
54813  JerEmY hArdIN JR.   89    Male         A+          Diabetes

      Date of Admission          Doctor                     Hospital  \
53825        19 01 2023     Mary Vaughn  and Perez, Bennett Townsend
52857        22 05 2022      Mark White     and Martin, Davidson Cox
52372        28 05 2021   Robert Garcia      and Miller, Olson Olson
54044         7 09 2021   Bridget Irwin                    PLC White
54813         5 11 2019  Willie Stevens                 Gray-Solomon

      Insurance Provider  Billing Amount  Room Number Admission Type  \
53825              Cigna     9542.739709          289      Emergency
52857              Cigna    48274.348630          332         Urgent
52372              Cigna     5692.907188          166       Elective
54044              Aetna     7628.951322          363       Elective
54813              Cigna     7242.641277          113       Elective

      Discharge Date   Medication  Test Results
53825     28 01 2023  Paracetamol      Abnormal
52857     26 05 2022   Penicillin  Inconclusive
52372     13 06 2021  Paracetamol      Abnormal
54044     24 09 2021      Aspirin      Abnormal
54813     28 11 2019   Penicillin        Normal

# 4. GroupBy and Aggregration

In [ ]:
# Group by 'Hospital' and calculate the mean of billing amount

grouped_df=df.groupby('Hospital')['Billing Amount'].mean()
print("Mean billing amount per hospital:\n", grouped_df)

Mean billing amount per hospital:
 Hospital
Abbott Inc                       38052.04192
Abbott Ltd                       29877.58648
Abbott Moore and Williams,       24799.59634
Abbott and Thompson, Sullivan    16738.56976
Abbott, Peters and Hoffman       18842.39686
                                    ...
and Zimmerman Sons               32706.65262
and Zuniga Davis Carlson,        42867.04130
and Zuniga Francis Peterson,     33689.63073
and Zuniga Sons                  33950.17048
and Zuniga Thompson, Blake       22067.42876
Name: Billing Amount, Length: 39876, dtype: float64

# 5. Data Cleaning and Manipulation

In [ ]:
df['Age'].fillna(df['Age'].mean(), inplace=True)
print("DataFrame with missing values filled:\n", df)

DataFrame with missing values filled:
                     Name  Age  Gender Blood Type Medical Condition  \
0          Bobby JacksOn   30    Male         B-            Cancer
1           LesLie TErRy   62    Male         A+           Obesity
2            DaNnY sMitH   76  Female         A-           Obesity
3           andrEw waTtS   28  Female         O+          Diabetes
4          adrIENNE bEll   43  Female        AB+            Cancer
...                  ...  ...     ...        ...               ...
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma
55496         KYle pEREz   61  Female        AB-           Obesity
55497       HEATher WaNG   38  Female         B+      Hypertension
55498     JENniFER JOneS   43    Male         O-         Arthritis
55499       jAMES GARCiA   53  Female         O+         Arthritis

      Date of Admission            Doctor                      Hospital  \
0            31 01 2024     Matthew Smith               Sons and Miller
1            20 08 2019   Samantha Davies                       Kim Inc
2            22 09 2022  Tiffany Mitchell                      Cook PLC
3            18 11 2020       Kevin Wells    Hernandez Rogers and Vang,
4            19 09 2022    Kathleen Hanna                   White-White
...                 ...               ...                           ...
55495        16 08 2020     Joshua Jarvis                Jones-Thompson
55496        23 01 2020   Taylor Sullivan                  Tucker-Moyer
55497        13 07 2020    Joe Jacobs DVM  and Mahoney Johnson Vasquez,
55498        25 05 2019    Kimberly Curry      Jackson Todd and Castro,
55499         2 04 2024     Dennis Warren                Henry Sons and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
0             Blue Cross    18856.281310          328         Urgent
1               Medicare    33643.327290          265      Emergency
2                  Aetna    27955.096080          205      Emergency
3               Medicare    37909.782410          450       Elective
4                  Aetna    14238.317810          458         Urgent
...                  ...             ...          ...            ...
55495         Blue Cross     2650.714952          417       Elective
55496              Cigna    31457.797310          316       Elective
55497   UnitedHealthcare    27620.764720          347         Urgent
55498           Medicare    32451.092360          321       Elective
55499              Aetna     4010.134172          448         Urgent

      Discharge Date   Medication  Test Results
0          2 02 2024  Paracetamol        Normal
1         26 08 2019    Ibuprofen  Inconclusive
2          7 10 2022      Aspirin        Normal
3         18 12 2020    Ibuprofen      Abnormal
4          9 10 2022   Penicillin      Abnormal
...              ...          ...           ...
55495     15 09 2020   Penicillin      Abnormal
55496      1 02 2020      Aspirin        Normal
55497     10 08 2020    Ibuprofen      Abnormal
55498     31 05 2019    Ibuprofen      Abnormal
55499     29 04 2024    Ibuprofen      Abnormal

[55500 rows x 15 columns]

<ipython-input-68-e2274a55f616>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)

In [ ]:
# Create a new column 'name_hospital' by combining 'Name' and 'Hospital'

df['name_hospital']=df['Name']+' '+df['Hospital']
print("DataFrame with new column:\n", df)

DataFrame with new column:
                     Name  Age  Gender Blood Type Medical Condition  \
0          Bobby JacksOn   30    Male         B-            Cancer
1           LesLie TErRy   62    Male         A+           Obesity
2            DaNnY sMitH   76  Female         A-           Obesity
3           andrEw waTtS   28  Female         O+          Diabetes
4          adrIENNE bEll   43  Female        AB+            Cancer
...                  ...  ...     ...        ...               ...
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma
55496         KYle pEREz   61  Female        AB-           Obesity
55497       HEATher WaNG   38  Female         B+      Hypertension
55498     JENniFER JOneS   43    Male         O-         Arthritis
55499       jAMES GARCiA   53  Female         O+         Arthritis

      Date of Admission            Doctor                      Hospital  \
0            31 01 2024     Matthew Smith               Sons and Miller
1            20 08 2019   Samantha Davies                       Kim Inc
2            22 09 2022  Tiffany Mitchell                      Cook PLC
3            18 11 2020       Kevin Wells    Hernandez Rogers and Vang,
4            19 09 2022    Kathleen Hanna                   White-White
...                 ...               ...                           ...
55495        16 08 2020     Joshua Jarvis                Jones-Thompson
55496        23 01 2020   Taylor Sullivan                  Tucker-Moyer
55497        13 07 2020    Joe Jacobs DVM  and Mahoney Johnson Vasquez,
55498        25 05 2019    Kimberly Curry      Jackson Todd and Castro,
55499         2 04 2024     Dennis Warren                Henry Sons and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
0             Blue Cross    18856.281310          328         Urgent
1               Medicare    33643.327290          265      Emergency
2                  Aetna    27955.096080          205      Emergency
3               Medicare    37909.782410          450       Elective
4                  Aetna    14238.317810          458         Urgent
...                  ...             ...          ...            ...
55495         Blue Cross     2650.714952          417       Elective
55496              Cigna    31457.797310          316       Elective
55497   UnitedHealthcare    27620.764720          347         Urgent
55498           Medicare    32451.092360          321       Elective
55499              Aetna     4010.134172          448         Urgent

      Discharge Date   Medication  Test Results  \
0          2 02 2024  Paracetamol        Normal
1         26 08 2019    Ibuprofen  Inconclusive
2          7 10 2022      Aspirin        Normal
3         18 12 2020    Ibuprofen      Abnormal
4          9 10 2022   Penicillin      Abnormal
...              ...          ...           ...
55495     15 09 2020   Penicillin      Abnormal
55496      1 02 2020      Aspirin        Normal
55497     10 08 2020    Ibuprofen      Abnormal
55498     31 05 2019    Ibuprofen      Abnormal
55499     29 04 2024    Ibuprofen      Abnormal

                                   name_hospital
0                  Bobby JacksOn Sons and Miller
1                           LesLie TErRy Kim Inc
2                           DaNnY sMitH Cook PLC
3        andrEw waTtS Hernandez Rogers and Vang,
4                      adrIENNE bEll White-White
...                                          ...
55495           eLIZABeTH jaCkSOn Jones-Thompson
55496                    KYle pEREz Tucker-Moyer
55497  HEATher WaNG and Mahoney Johnson Vasquez,
55498    JENniFER JOneS Jackson Todd and Castro,
55499                jAMES GARCiA Henry Sons and

[55500 rows x 16 columns]